on:
  push

env:
  IMAGE_VERSION: 1.6

name: Test

jobs:
  Test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: docker run -v `pwd`:/project krystian8207/rst:$IMAGE_VERSION bash -c "R -e 'testthat::test_local()'"
